version = 1

test_patterns = [
    "/api/*",
    "script.js"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  style_guide = "airbnb"
  